language: node_js
node_js: "12"
cache:
  directories:
    - maas-schemas/node_modules # Our node modules
    - $HOME/.npm # Globally installed packages, e.g. NPM

install:
  - yarn --cwd maas-schemas
  - yarn --cwd maas-schemas upgrade # Ensure to use latest versions of dependencies
  - yarn --cwd maas-schemas-ts

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - yarn --cwd maas-schemas ci
        - yarn --cwd maas-schemas-ts ci
    - stage: deploy
      script:
        - yarn --cwd maas-schemas build
        - yarn --cwd maas-schemas docs
        - echo Deploying docs to GitHub pages of ${TRAVIS_REPO_SLUG}
        - git remote add origin-pages https://${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - yarn --cwd maas-schemas gh-pages -o origin-pages
      before_deploy:
        - cd maas-schemas
      deploy:
        provider: npm
        email: tech@maas.global
        skip_cleanup: true
        api_key: $NPM_TOKEN
      after_deploy: ./maas-schemas/scripts/tag.sh
